- apps/web/src/components/Main.tsx
This PR enables submit on "Enter" in the textbox and newlines with (Shift + Enter). Following common chat box convention.
> Change "Enter" submit logic

- apps/cf-ai-backend/package.json
- apps/cf-ai-backend/src/OpenAIEmbedder.ts
- apps/web/package.json
- package.json
This bumps `workers-types`, and then removes the no longer needed `@cloudflare/ai` package. That package is now deprecated:
https://developers.cloudflare.com/workers-ai/changelog/
> chore: remove @cloudflare/ai package

- apps/extension/manifest.json
This change resolves #17 by a new manifest.json which is compatible with Firefox for Manifest V3.
Signed-off by Aaron Chu-Carroll
adchucarroll@gmail.com
> Edit manifest.json for Firefox support

- apps/web/app/(landing)/Cta.tsx
Fixes the Call to Action component background color by changing it from black to secondary background color.
- Updated the background color of the Call to Action component from black to secondary background color.
- Improved the visual consistency by matching the background color with the design.
- Modified the CSS class in Cta.tsx to reflect the new background color setting.
- Included before and after images to illustrate the color change.
<details>
Call to action background image has rounded with bg color as black on all four corners.
So, i changed to bg secondary to match
</details>
> fix: Cta component background color

- apps/web/app/(landing)/Headers/Navbar.tsx
- apps/web/app/(landing)/Showcase.tsx
Updated Navbar text style and made spacing & color fixes in the showcase section.
- Updated the Navbar text style from uppercase to lowercase for better readability.
- Made minor spacing adjustments in the showcase section for improved design and user experience.
- Adjusted the color of the active feature indicator in the showcase section from blue to indigo for better contrast and visual appeal.
- Fixed the color issue in the showcase section by changing the text color from blue to gray for improved readability.
- Added `focus:outline-none` to the feature button class in the showcase section to remove unwanted focus outlines when clicked.
- Adjusted the vertical spacing of the feature heading and description in the showcase section for better alignment and readability.
Changes have been …
> Fix: Nav & Showcase section

- apps/web/app/(landing)/Cta.tsx
Resolved the sign-in link z-index issue for the rotating icons on the website.
- **Issue**: The pull request addressed the z-index problem with the sign-in link below the rotating icons.
- **Solution**: Added a z-index of 1 to the link element within the Cta.tsx component.
- **Impact**: The intended behavior of triggering the link and the TEXT ITSELF when clicking on the sign-in arrow has been restored.
- **Reference**: Please see the provided image for the comparison:[Image](https://github.com/Dhravya/supermemory/assets/133845351/130f757b-f110-42b8-a2ed-1153935fcbb8)
- **Code Change**: The z-index property was added dynamically using `z-[1]` with the relative positioning to ensure proper stacking order for elements in the CSS.
<details> …
> fixed link

- apps/web/app/(auth)/signin/page.tsx
Renames the '/terms' page to '/tos' to fix a 404 error.
- The '/terms' page was returning a 404 error because the terms of service page is actually located at '/tos'.
- Updates the link in the Sign In page from '/terms' to '/tos' to correctly point to the terms of service page.
- This is a minor change to fix a broken link and ensure the terms of service page is accessible to users.
<details>
The /terms page is giving a 404 error because the terms of service page is named /tos
</details>
> rename terms to tos

- apps/web/app/(dash)/menu.tsx
This pull request reduces the size of the Menu component.
- The `rows` attribute of the `textarea` element in the `Menu` component has been reduced from 8 to 4.
- This change aims to make the menu more compact and visually appealing.
- The menu previously occupied too much space on the screen, leading to this adjustment.
<details>
None
</details>
> menu reduced size

- .vscode/settings.json
- packages/ui/icons/index.ts
- packages/ui/tsconfig.json
- packages/ui/tsconfig.lint.json
- packages/ui/types.d.ts
This pull request addresses a TypeScript import error related to SVG files in the UI package. The issue was caused by the inability to find the corresponding type declarations for the SVG imports.
- Key Changes:
- Updated the `.vscode/settings.json` file to use the TypeScript SDK from the project's `node_modules` directory instead of the global VSCode installation.
- Added a `types.d.ts` file in the `ui` package to provide type declarations for SVG imports.
- Refactoring:
- Removed the unused `blockIcon` import from the `ui/icons/index.ts` file.
This change should resolve the TypeScript import error for SVG files in the UI package, allowing the project to build and run without issues related to missing type declarations.
<details>
<summary>Original …
> fix(ui, repo): resolve typescript svg import error

- apps/web/app/(dash)/header/header.tsx
This pull request improves the accessibility and mobile responsiveness of the history dropdown in the web application's header.
- Replaced the custom history dropdown implementation with the `@repo/ui/shadcn/dropdown-menu` component for improved accessibility and consistency.
- Added `CaretDownIcon` from `@radix-ui/react-icons` to visually indicate the dropdown.
- Updated styling and layout for better mobile responsiveness.
- None
- Replaced custom dropdown with a standardized component.
<details>
This pull request addresses accessibility and mobile UI issues with the history dropdown in the web application's header.
- Replaced the …
> fix(web): history a11y and mobile issues

- apps/web/app/(dash)/(memories)/content.tsx
- apps/web/app/(dash)/header/autoBreadCrumbs.tsx
This pull request addresses issue #148 by enhancing the `autoBreadcrumb` component to improve navigation for users accessing the "spaces" section of the application. It modifies the breadcrumb behavior to ensure that clicking on the "space" breadcrumb redirects users to the appropriate memories view.
- Key Changes:
- Updated the `autoBreadcrumb` component to manually override the href for the "space" breadcrumb, directing users to `/memories?tab=spaces`.
- Implemented the use of the `next/navigation` package in the `MemoriesPage` to fetch query parameters and set the initial filter state based on the `tab` parameter.
- Users can now click on the "space" breadcrumb to directly view their spaces, enhancing the user experience by eliminating an extra navigation step.
- …
> Fix Spaces Breadcrumb

- apps/web/app/(dash)/(memories)/content.tsx
This pull request addresses an issue where the link of a note in the "Memories" section was overflowing and not being properly formatted, unlike the formatting for the pages. The goal is to ensure consistent formatting and prevent the link from overflowing.
- Key Changes: Added the `truncate` class from Tailwind CSS to the link component in the `content.tsx` file, which applies the following styles to handle overflow:
- `overflow: hidden;`
- `text-overflow: ellipsis;`
- `white-space: nowrap;`
- Refactoring: No major refactoring changes were made, the fix was a targeted update to the existing code.
<details>
This pull request addresses an issue where the link of a note in the "Memories" section was overflowing and …
> Update line of memories to not overflow

- apps/web/app/(auth)/onboarding/page.tsx
- apps/web/app/(dash)/home/filterSpaces.tsx
- apps/web/app/(dash)/home/page.tsx
- apps/web/app/(dash)/home/queryinput.tsx
- packages/ui/shadcn/switch.tsx
This pull request introduces changes to the layout and structure of the home page, without modifying the color scheme. The main focus is on improving the overall visual presentation and user experience of the application.
- The main content area has been moved up to start at a higher position on the page, reducing the empty space above the content.
- The search input field has been modified to expand in width when there are selected spaces, providing a more compact and focused interface.
- The "History" component has been wrapped in a motion animation, making it fade in and out based on the presence of a search query.
- None
- The `QueryInput` component has been updated to adjust the height of the textarea based on the length of the query, providing a more responsive and visually …
> home layout change (without color change)

- apps/web/app/(dash)/chat/chatWindow.tsx
- package.json
This pull request addresses the issue of external links opening in the same tab when clicking on a memory in the chat window. The changes ensure that external links are opened in a new tab, improving the user experience.
- Key Changes: Added `target="_blank"` and `rel="noopener noreferrer"` attributes to the `Link` component for external sources in the `chatWindow.tsx` file.
- Refactoring: Restored the necessary files and removed the `wrangler.toml` from the `.gitignore` file without pushing it to deployment.
<details>
This PR addresses the issue of external links opening in the same tab. I've added target="_blank" rel="noopener noreferrer" to the Link component for external sources. I am raising this second pr …
> Fix/clicking on a memory should open it in a new tab #167 (2)

- apps/web/app/(dash)/menu.tsx
- apps/web/lib/useKeyPress.ts
This pull request introduces a custom `useKeyPress` hook for handling keyboard events and adds a keyboard shortcut (ALT+a) to open the memory creation dialog.
- Added `useKeyPress` hook to `lib/useKeyPress.ts` for detecting key presses.
- Implemented ALT+a shortcut in `(dash)/menu.tsx` to open the memory creation dialog.
- Added a new keyboard shortcut for creating memories.
- No significant refactoring changes.
<details>
Fixes: #178 
Added a custom hook for implementing keymaps to enhance the user experience.
Added keymap (ALT+a) for adding a memory. 
</details>
> Add useKeyPress hook for keyboard event handling

- apps/web/app/(thinkpad)/thinkpad/page.tsx
This pull request renames the "Canvas" feature to "Thinkpad" throughout the codebase.
- Key Changes:
- Renamed "Canvas" to "Thinkpad" in the page title and description.
- Updated the beta message to reflect the new name.
- New Features: None
- Refactoring: None
<details>
None
</details>
> It's 'Thinkpad' not Canvas anymore

- apps/web/app/(thinkpad)/thinkpad/page.tsx
This pull request centers the content of the "thinkpad" page on the web application.
- Key Changes: Adjusted the CSS class on the main container div to add the `justify-center` utility, centering the content horizontally.
- New Features: None
- Refactoring: None
<details>
None
</details>
> chore(ui): justify thinkpad to center

- apps/web/app/(dash)/menu.tsx
This pull request addresses issue #146 by implementing a solution to prevent multiple submissions of a form, which was causing memory-related bugs. The main change involves utilizing the `useFormStatus` hook to manage the state of the submit button, ensuring it is disabled during form submission.
- Introduced the `SubmitButton` component that leverages `useFormStatus` to disable the button when a submission is in progress.
- Removed the inline button definition from the `DialogFooter` and replaced it with the new `SubmitButton` component for better encapsulation and readability.
- The `SubmitButton` component provides a more user-friendly experience by preventing multiple submissions, thereby enhancing form reliability.
- The button logic …
> fixes #146 multiple memory submission bug

- apps/web/app/api/telegram/route.ts
This pull request enhances the Telegram bot by enabling Markdown support for improved message formatting.
- Key Changes:
- Added `parse_mode: "MarkdownV2"` to `ctx.reply` and `ctx.api.editMessageText` calls to enable Markdown formatting.
- Markdown support for bot messages.
- Refactoring:
- None.
<details>
None
</details>
> chore: Update Telegram bot with Markdown Support

- apps/web/next.config.mjs
Do this until https://github.com/vercel/next.js/pull/68930 is published
This pull request optimizes the Next.js configuration for the web application, focusing on improving the development experience and enabling Turbopack support.
- Key Changes:
- Conditionally apply the MillionLint Next.js plugin when in development mode and Turbopack is not enabled.
- Enable the `rsc` (React Server Components) option when using the MillionLint plugin.
- Update the `eslint` configuration to ignore linting errors during builds.
- Introduce support for Turbopack, a new fast bundler for Next.js, when the `TURBOPACK` environment variable is set.
- Refactoring:
- Reorganize the Next.js configuration to separate the base configuration from the development-specific configuration.
<details>
> ✨ …
> fix: Disable Million if turbopack is enabled

- README.md
- **Purpose:**
Correct the URL for the authkit-remix-cloudflare repository.
- Updated the link for authkit-remix-cloudflare from `supermemory` to `supermemoryai`.
- **Impact:**
Ensures users access the correct repository for the authentication kit.
<details>
None
</details>
> Fix broken Authkit URL in README

- apps/web/app/components/memories/AddMemory.tsx
Updated AddMemory.tsx component to fix overflow memory category/tabs UI  while selecting the category of the new memory
before: ![image](https://github.com/user-attachments/assets/a27c7e4e-6323-45da-808c-376e7271fc19)
after: ![image](https://github.com/user-attachments/assets/8fc91292-6314-4a09-a499-f281f4f05137)
> Updated AddMemory.tsx component to fix overflow memory category/tabs UI  

- apps/web/components/menu.tsx
Previously, the badge with the memories limit in the consumer app menu was cut off on desktop, and now with this PR, it no longer is.
> fix: memory limits cutoff

- apps/web/components/menu.tsx
Before
After
- Reduced menu hover width from 220px to 160px
- Simplified text positioning from absolute positioning to padding-left
- Removed the usage limit warning badge from the desktop menu
> refactor(ui): optimize menu hover width and simplify text layout

- apps/web/app/onboarding/progress-bar.tsx
> ui: fix progress bar thickness on regular browser

- apps/web/components/chrome-extension-button.tsx
- apps/web/components/content-cards/website.tsx
- apps/web/components/header.tsx
- apps/web/components/masonry-memory-list.tsx
- apps/web/components/memories-utils/memory-detail.tsx
- apps/web/components/memory-list-view.tsx
- apps/web/lib/document-icon.tsx
Improved memory detail UI with better document icons and layout and Added dark mode support to the Chrome extension button
- Enhanced the WebsiteCard component with an `onOpenDetails` prop
- Improved the MemoryDetail component with:
- Better layout for document headers and source links
- Enhanced content scrolling with proper height constraints
- Improved spacing and padding in various sections
- Added favicon support to document icons, showing website favicons for webpage documents
- Fixed document type detection for webpages and URLs
- Added dark mode support to the Chrome extension button component with appropriate color classes
[Screen Recording 2025-10-03 at 11.34.01 PM.mov <span class="graphite__hidden">(uploaded via Graphite)</span> <img class="graphite__hidden" …
> feat: url cards as content preview with rich details
