apps/web/next.config.mjs

ignore eslint and ts build errors

speed up builds

---

apps/web-v2/src/app/(landing)/Cta.tsx
apps/web-v2/src/app/(landing)/EmailInput.tsx
apps/web-v2/src/app/(landing)/FeatureContent.tsx
apps/web-v2/src/app/(landing)/Features.tsx
apps/web-v2/src/app/(landing)/Hero.tsx
apps/web-v2/src/app/(landing)/Navbar.tsx
apps/web-v2/src/app/(landing)/footer.tsx
apps/web-v2/src/app/(landing)/linkArrow.tsx
apps/web-v2/src/app/(landing)/page.tsx
apps/web-v2/src/app/globals.css
apps/web-v2/src/components/ui/cardClick.tsx
apps/web-v2/src/utils/cn.ts

switching to linux was a mistake, can't even record good previews :(

landing page improved for readability and smooth scroll

---

apps/cf-ai-backend/src/utils/chonker.ts
apps/cf-ai-backend/src/utils/seededRandom.ts

Add JSDoc comments to two utility functions for better code documentation.
- Added JSDoc comments to describe the purpose of the 'chunkText' function in 'chonker.ts'.
- Added JSDoc comments to explain the hashing process and purpose of 'hashString' function in 'seededRandom.ts'.
- Introduced JSDoc comments to document the functionality of the 'seededRandom' function generating random numbers based on a seed.
<details>
I was just exploring the AI code and thought to add some js docs, for others 
</details>

add js docs

---

apps/web/components/canvas/textCard.tsx

Minor improvements to the text card component's styling.
This pull request proposes some minor updates to the text card component's CSS styles:
- Changed the background color from `#2C3439` to `#2d333a`.
- Added a border of `2px solid #3e4449`.
- Set the overflow property to `auto`.
These changes primarily focus on enhancing visual cues and allowing for better handling of text content that might exceed the card's dimensions.
<details>
None
</details>

dhravya's improvements

---

apps/web/app/(landing)/Cta.tsx
apps/web/app/(landing)/footer.tsx

Improved the CTA and Footer components on the landing page with updated layout and responsiveness.
- The **CTA (Call-To-Action) component** has received a layout update by changing the `w-full` class to `w-fit` to optimize the width on large screens and make the CTA button more visually appealing.
- The **Footer component** has been made more responsive by updating the `flex` class property to `flex justify-around` to adjust the alignment of the items on smaller screens, and hiding the link arrow on medium and smaller screens by adding `hidden md:block` to improve visual presentation. The class `text-center` has also been added on the footer to make the text well-centered on smaller screens.
<details>
Before …

refactor: Update Cta and Footer components on the landing page

---

README.md

Update og image URL and website link in the README file.
This pull request aims to update the following:
- The `og image` URL in the **og image** section.
- The website link to access SuperMemory and sign-in with a Google account.
The following changes were made in the `README.md` file:
- The `og image` URL has been updated to `https://supermemory.ai/og-image.png` from `https://supermemory.dhr.wtf/og-image.png`.
- The website link to access SuperMemory has been updated to `https://supermemory.ai` from `https://supermemory.dhr.wtf` in the **How do I use this?** section.
These changes enable users to access the latest SuperMemory website using the updated URL. Additionally, the updated `og image` URL will ensure a consistent and correct image is displayed when sharing the website on various …

Update og image URL and website link

---

README.md

Update README.md with new UI screenshots and download link
This pull request updates the `README.md` file with new UI screenshots, improves the description of the Chrome extension, and provides a link for downloading the extension from the Chrome Web Store. Below are the key changes:
- The old instructions for getting and authorizing the Chrome extension have been replaced with a direct link to the Chrome Web Store, making it easier for users to install the extension.
- The new Chrome extension UI screenshot showcases the extension's new design and functionality.
- The description of the Chrome extension has been revised to provide better context on its usage and importance, along with a note that the extension is not required to use the app.
- The old UI screenshot of the app has been …

Update README.md with new UI

---

apps/web/app/(dash)/(memories)/content.tsx

Fixes filters in space and memories by introducing new filter methods.
- The pull request modifies the `Filters` component in the `content.tsx` file.
- The `Filters` component now accepts an additional prop `filterMethods` which is used to determine the available filter options.
- The `filterMethods` prop is set dynamically based on the `currentSpace` variable. If `currentSpace` is present, `SpaceFilterMethods` are used; otherwise, `MemoriesFilterMethods` are used.
- Two new arrays, `MemoriesFilterMethods` and `SpaceFilterMethods`, are introduced to define the filter options for memories and spaces respectively.
- The `FilterMethods` array, which was previously used to define the filter options, is replaced with the `filterMethods` prop.
<details> …

fix: filters in space and memories

---

.prettierrc
apps/cf-ai-backend/src/helper.ts
apps/cf-ai-backend/src/index.ts
apps/web/app/actions/doers.ts

This pull request introduces a new feature for storing and retrieving chunks of text from a vector database, along with improved error handling for processing large documents.
- **New Feature: Chunk ID's in Database:**
- Added functionality to store chunk ID's in the database, allowing for efficient retrieval of specific chunks of text.
- Implemented a new `batchCreateChunksAndEmbeddings` function in `helper.ts` to handle the creation and storage of chunks.
- Modified the `index.ts` file to return the chunked input, which includes the chunk ID's and corresponding text.
- **Improved Error Handling:**
- Enhanced error handling in `web/app/actions/doers.ts` to provide more informative error messages when processing large documents.
- Added a check in `index.ts` to prevent the processing of …

show chunks seperations in database, proper error handling and prettier config

---

apps/web/app/(dash)/(memories)/content.tsx

This pull request updates the `contents.ts` component to open the memory cards link in a new tab.
- The `Link` component in the `contents.ts` file now includes the `target='_blank'` attribute to open the memory cards link in a new tab.
- This change ensures users can access the memory cards website without leaving the current page.
<details>
None
</details>

Update content.jsx the memory cards link opens in new tab

---

apps/web/app/(dash)/menu.tsx
packages/ui/shadcn/combobox.tsx
packages/ui/shadcn/command.tsx

This pull request introduces a significant overhaul of the application's user authentication and authorization system, with the goal of improving security and user management capabilities.
- Implemented a new authentication flow using JSON Web Tokens (JWT) for secure user login and session management.
- Introduced role-based access control (RBAC) to grant fine-grained permissions to users based on their assigned roles.
- Refactored the existing user management module to support the new authentication and authorization mechanisms.
- Added support for multi-factor authentication, allowing users to enable additional security measures like SMS or authenticator app-based verification.
- Improved password hashing and salting algorithms to enhance the overall security of user credentials.
- …

more improved ui

---

apps/web/app/(dash)/home/page.tsx

This pull request aims to improve user experience by replacing standard `<a>` tags with Next.js `<Link>` components and adding a hovering animation to links.
- Replaced `<a>` tags with `<Link>` components for better prefetching and SEO.
- Added a hovering animation to links for improved user responsiveness.
- Hovering animation for links.
- Replaced `<a>` tags with `<Link>` components.
<details>
- Adding Hovering animation for user responsiveness 
- Using NextJs is Link tag rather than a tag since Link Tags prefetch pages
- (Have not tested though please test before deployment)
</details>

feat/refactor: Using <Link> instead of <a> and hovering animation

---

apps/web/app/(dash)/dialogContentContainer.tsx
apps/web/app/(dash)/menu.tsx

This pull request addresses an issue with the blur effect in the "Add Memory Card" component by removing the `backdrop-blur-md` Tailwind CSS class. The changes enhance the visual clarity of the component, improving the user experience.
- Removed the `backdrop-blur-md` class from the `DialogContent` component in both `dialogContentContainer.tsx` and `menu.tsx`.
- No new features were introduced in this pull request.
- The code was simplified by eliminating the unnecessary blur effect, which may also contribute to better performance and readability.
<details>
fixed the blur in the add memory card/component by removing a tailwind class backdrop-blur-md. made changes …

fixed the blur in the add memory card/component

---

apps/web/app/(landing)/Hero.tsx

This pull request adds a Product Hunt "Top Post of the Day" badge to the landing page of the Supermemory application. The badge will showcase the product's recognition on Product Hunt, a popular platform for discovering new and innovative products.
- Key Changes: Added a new `<a>` element with an embedded Product Hunt badge image to the landing page's hero section.
- New Features: Integrated the Product Hunt "Top Post of the Day" badge to highlight the application's recognition on the platform.
- Refactoring: Adjusted the layout and styling of the hero section to accommodate the new badge without disrupting the existing content and design.
<details>
</details>

add: producthunt of the day badge to landing page

---

SETUP-GUIDE.md

This pull request introduces a comprehensive guide for self-hosting Supermemory, covering both frontend and backend setup. It provides detailed instructions for setting up the necessary infrastructure, including Cloudflare Workers, R2 storage, and D1 database, along with configuration steps for both the web application and the AI backend.
- Key Changes:
- Added a dedicated "Self Hosting Guide" document.
- Provided step-by-step instructions for setting up the web application and AI backend.
- Included information on required prerequisites, such as Bun, Turbo, Wrangler, and Yarn.
- Detailed the creation of KV namespaces and R2 buckets for both frontend and backend.
- Explained the configuration of D1 databases for the web application.
- Emphasized the importance of setting up OAuth …

docs: self hosting guide

---

apps/web/app/(dash)/(memories)/content.tsx

This pull request addresses the overflow issue identified in issue #168 by modifying the CSS properties of the URL display within the `LinkComponent`. The changes ensure that long URLs are properly truncated, enhancing the user interface and preventing layout disruptions.
- Updated the `div` containing the URL to include the classes `overflow-hidden`, `text-ellipsis`, and `whitespace-nowrap`, which effectively manage long text overflow.
- No new features were introduced in this pull request; the focus was solely on fixing an existing issue.
- Minimal refactoring was performed; however, the change improves the overall readability and maintainability of the component by clarifying the intent of the CSS classes applied.
> ✨ Generated with love …

fixes for issue #168

---

apps/cf-ai-backend/src/helper.ts
apps/cf-ai-backend/src/index.ts
apps/cf-ai-backend/src/utils/chunkTweet.ts
apps/web/app/actions/doers.ts

This pull request addresses issues with the handling of tweets and sources in the `api/chat` endpoint of the CF-AI-Backend application. The changes aim to improve the processing and storage of tweet and source data to ensure accurate and reliable information is provided in the API response.
- Improved handling of tweet data, including parsing raw tweet JSON and extracting relevant metadata such as tweet ID, links, videos, and images.
- Implemented more robust error handling when fetching thread data from the external service, ensuring the API can gracefully handle cases where the thread data is empty or invalid.
- Adjusted the logic for populating the `vectorData` variable, using the tweet content as a fallback when there are issues fetching the thread data.
- None
- Moved the tweet data …

fix tweets and sources

---

README.md

This pull request updates the README file to accurately reflect the current status of the Chrome extension associated with the Supermemory project, ensuring that users have the most relevant information regarding the extension's availability.
- Key Changes: The outdated note indicating that the Chrome extension on the web store is not updated has been removed to prevent user confusion.
- New Features: None identified in this pull request.
- Refactoring: The README text has been streamlined for improved clarity and readability, enhancing the overall user experience.
<details>
This pull request updates the README file to reflect the current status of the Chrome extension …

The extension is up-to date now

---

apps/web/app/(thinkpad)/thinkpad/image.tsx

This pull request addresses a typo in the `ImageComponent` within the Thinkpad application.
- Key Changes:
- Corrected the typo "Drew things to seee here" to "Draw things to see here" within the `ImageComponent`.
<details>
None
</details>

Fix 'Draw things to see here'

---

apps/web/app/(dash)/menu.tsx

This pull request integrates a promise-based toast notification system to provide more informative feedback during memory creation.
- Key Changes:
- Replaced direct `toast.info`, `toast.error`, and `toast.success` calls with `toast.promise` for memory creation.
- Modified the `handleSubmit` function to return a promise that resolves with the result of the memory creation API call.
- Added error handling within the `toast.promise` configuration to display appropriate messages based on success or failure.
- None
- Refactoring:
- None
<details>
Fixes: #170 
</details>

Sonner promise toaster added

---

apps/web/app/(auth)/signin/page.tsx

This pull request addresses an issue with the Telegram bot link in the sign-in page of the web application. It ensures that the Telegram user information is properly passed as a query parameter when redirecting the user to the home page after successful sign-in.
- Key Changes: Updated the redirect logic in the `Signin` component to include the `telegramUser` query parameter if it is present in the search parameters.
- New Features: None
- Refactoring: None
<details>
None
</details>

fix telegram bot link issue

---

apps/web/app/(auth)/onboarding/page.tsx
apps/web/app/(dash)/chat/chatWindow.tsx

This pull request introduces text-to-speech functionality for chat answers, allowing users to hear the AI's responses read aloud. #197 
- Added a speaker icon button to the chat window.
- Implemented text-to-speech using the `SpeechSynthesis` API.
- Text-to-Speech for chat answers.
- Minor formatting changes using Prettier.
- Improved error handling in the onboarding page.
<details>
added tts using the `SpeechSynthesis` API. 
other changes are for formatting, prettier
</details>

feat: text to speech on answers

---

apps/web/app/(dash)/chat/chatWindow.tsx
apps/web/wrangler.toml

This pull request adds the ability to stop the text-to-speech (TTS) functionality for the current chat response. It also modifies the behavior of the TTS button to indicate the speaking state and disable the button when another response is being spoken.
- Key Changes:
- Added a `speakingIdx` state to track the index of the chat response currently being spoken.
- Implemented `handleTTS` and `stopTTS` functions to start and stop the TTS, respectively.
- Updated the TTS button to show a "stop speaking" icon when the current response is being spoken, and a "speaker" icon otherwise.
- Disabled the TTS button when another response is being spoken.
- Added the ability to stop the TTS of the current chat response.
- Refactoring:
- Removed the previous TTS functionality that was …

Textospeech

---

apps/web/app/(dash)/(memories)/content.tsx
apps/web/app/actions/doers.ts

This pull request introduces a new feature to delete spaces, along with UI improvements and logic changes. It addresses issue #143.
- Added `deleteSpace` function to the `doers.ts` file for deleting spaces from the database.
- Implemented `handleDeleteSpace` function in `content.tsx` to handle the deletion process.
- Updated the `MemoriesPage` component to display a delete icon next to each space, allowing users to delete them.
- Modified the `TabComponent` to include a delete icon and handle the deletion event.
- Added a delete space feature to the application.
- Removed unused imports in `content.tsx`.
- Updated the `MemoriesPage` component to use the new `spaces` state instead of `memoriesAndSpaces.spaces`.
> ✨ Generated with …

feat: delete space

---

README.md

Issue: #208 
This pull request addresses a minor typographical error in the `README.md` file, enhancing the clarity and professionalism of the documentation by correcting the spelling of "Volia" to "Voila" in the "Import Twitter Bookmarks" section.
- Corrected the spelling of "Volia!" to "Voila!" in the README.
- None.
- None.
<details>
This pull request addresses a minor typo in the `README.md` file. The word "Volia!" in the "Import Twitter Bookmarks" section has been corrected to "Voila!" to ensure accurate spelling.
- **File Updated**: `README.md`
- **Section**: "Import Twitter Bookmarks"
- **Change**: Replaced "Volia!" with "Voila!" to …

#208 - Correct Typo in README.md: Change "Volia" to "Voila"

---

README.md

This pull request updates the README.md file to capitalize "Chrome extension" for consistency and improved readability.
- Key Changes:
- Updated "chrome extension" to "Chrome extension" in the documentation.
- None
- Refactoring:
- None
<details>
This pull request makes a minor but important change to the README.md file. The term "chrome extension" has been capitalized to "Chrome extension" to enhance consistency and modularity in the documentation. This change aligns with standard naming conventions and improves readability.
- Updated "chrome extension" to "Chrome extension" in the documentation.
This small adjustment ensures that our documentation adheres to a uniform …

Capitalize "Chrome extension" for Better Modularity

---

SETUP-GUIDE.md

This pull request addresses a spelling error in the introduction section of the *Self-Hosting Guide*, enhancing the document's clarity and professionalism.
- Key Changes: Corrected the spelling of *"neccessary"* to *"necessary"* in the introduction section of the guide.
- New Features: None.
- Refactoring: None.
<details>
#210 
This pull request addresses a spelling mistake in the introduction section of the *Self-Hosting Guide. The word *"neccessary"* was incorrectly spelled and has been corrected to *"necessary."** This change improves the clarity and professionalism of the document.
- Corrected the spelling of *"neccessary"* to *"necessary"* in the introduction section of the guide.
- …

#210 - Correct Typo: "Neccessary" to "Necessary" in Introduction of Self-Hosting Guide

---

apps/web/app/(dash)/chat/chatWindow.tsx
apps/web/tailwind.config.ts
packages/ui/shadcn/accordion.tsx

```markdown
This pull request enhances the chat window's UI and functionality by adding a horizontal scroll bar for related memories and a fade-out effect for content on the right side of the scrollable area.
- Implemented horizontal scroll handling with smoother transitions using `overflow-x-auto` and `scrollbar-thin` classes.
- Added a fade-out effect for right-side content in scrollable areas using a custom CSS gradient.
- Applied custom scrollbar styling for improved visibility and consistency.
@@ -10,6 +29,8 @@
- None
+    - The `AccordionContent` component has been modified to include scroll handling logic and a fade-out effect.
+    - The `ChatWindow` component now uses the updated `AccordionContent` component.
- None
```
> …

Scroll Bar for related memories inside chat window

---

apps/web/app/(dash)/chat/chatWindow.tsx
apps/web/app/(dash)/home/queryinput.tsx

This pull request enhances the markdown rendering within the chat window, improving the display of code blocks and other markdown elements.
- Key Changes:
- Updated the markdown rendering library to improve code block display.
- Applied CSS classes to the chat answer section for better styling.
- None
- Refactoring:
- Removed unnecessary `pro-mode` toggle element.
<details>
None
</details>

Better markdown Rendering

---

README.md

This pull request enhances the README file by adding hyperlinks to the official documentation for "Nextjs 14" and "Cloudflare Ratelimiter." This improvement aims to provide users with direct access to relevant resources, thereby improving the overall user experience and ensuring consistency within the documentation. 
Resolves #217 
- Key Changes:
- Added a hyperlink to the Next.js 14 documentation.
- Added a hyperlink to the Cloudflare Ratelimiter documentation.
- None specified; the changes focus on documentation enhancement.
- Refactoring:
- Improved the structure of the "Built with" section by converting plain text entries into clickable links, enhancing readability and usability.
<details>
<summary>Original …

Added Missing Documentation Links for "Nextjs 14" and "Cloudflare Ratelimiter" in README

---

apps/extension/content/ContentApp.tsx

This pull request adds a "View" button to the toast notification displayed after successfully saving content to supermemory.ai. This button allows users to directly access the saved content on the supermemory.ai website.
- Key Changes:
- Added a "View" button to the toast notification.
- The button opens the supermemory.ai website in a new tab.
- Added a new feature allowing users to view saved content directly from the extension.
- Refactoring:
- No refactoring changes were made.
<details>
None
</details>

feat: Add "View" button for chrome extension

---

apps/web/app/(dash)/menu.tsx

This pull request addresses a potential issue with memory queueing and enhances the form submission process for adding memories.
- Moved the `toast.promise` call outside the `handleSubmit` function to ensure proper error handling and loading state management.
- Replaced the direct call to `handleSubmit` within the form with a dedicated `formSubmit` function for better organization and reusability.
- Removed unnecessary error handling within `handleSubmit` as it's now handled by `toast.promise`.
- None
- Refactored the form submission logic to improve readability and maintainability.
<details>
I was not able to test it completely, …

memory queue fix

---

apps/cf-ai-backend/src/index.ts
apps/cf-ai-backend/src/queueConsumer/index.ts
apps/cf-ai-backend/src/types.ts

This pull request addresses two issues in the `cf-ai-backend` application:
1. Fixing the handling of spaces in the `vectorBody` schema.
2. Correcting the title field in the stored content metadata.
- Key Changes:
- Updated the `vectorBody` schema to use an array of numbers instead of strings for the `spaces` field.
- Fixed the `title` field in the stored content metadata to use the correct `metadata.title` value instead of the `metadata.description`.
- Refactoring:
- Removed unnecessary console logs and debugging statements.
- Simplified the logic for checking if content already exists in the database.
The main purpose of this pull request is to address issues related to the handling of spaces and the title field in the memory sources feature of the `cf-ai-backend` application. The …

fix spaces; fix incorrect title for memory sources

---

apps/extension/content/ContentApp.tsx

This pull request aims to enhance the content saving mechanism in the ContentApp component. The changes focus on improving the timer and save functionality to provide a more reliable and responsive user experience.
- Key Changes:
- Refactored the timer logic to use a separate `saveTimeoutRef` to schedule the content save after the timer completes.
- Implemented a `scheduleSave` function to manage the save timeout and ensure that the content is saved only once the timer has completed.
- Added cleanup logic in the `useEffect` hook to stop the timer and clear the save timeout when the component is unmounted or the popover is closed.
- None
- Refactoring:
- Improved type safety by using a custom `TimerId` type for the timer references.
- Simplified the timer start and stop …

fix: infinite save issue and improve timer logic in ContentApp

---

apps/web/app/(dash)/(memories)/content.tsx

This pull request introduces enhancements to the Memories Page by integrating a JSON export feature and refining the filter component's UI. The changes aim to improve user experience and maintainability of the code.
- Added a JSON export button to facilitate data export from the Memories Page.
- Moved the Filters component above the content for better accessibility and usability.
- Implemented a JSON Export button that triggers the `handleExport` function.
- Removed duplicate Filters component code to streamline the layout.
- Enhanced the button styling within the Filters component to improve visual feedback when a filter is selected, utilizing motion effects for better user interaction.
> ✨ Generated with love by …

little animation will be better

---

apps/web/app/(landing)/Navbar.tsx

This pull request introduces enhancements to the Navbar component, focusing on improving the visibility behavior during scroll events and refining the animation properties for a smoother user experience.
- Adjusted the calculation of the scroll direction to use `const` for better readability and performance.
- Modified the initial Y position of the navbar from `-130` to `-150` to improve the off-screen state.
- Updated the animated Y position when visible from `0` to `-50` for a more dynamic entrance.
- Added an easing function to the transition for smoother animations.
- Changed the class definition to use `inset-x-0` for better positioning across different screen sizes.
- None specified, but the animation improvements enhance the user experience.
- …

Navbar glitch fix

---

apps/web/app/(landing)/Cta.tsx

This pull request enhances the Call to Action (Cta) component by updating the messaging and improving the user engagement prompts. The changes aim to better align the component's content with the product's branding and encourage user interaction.
- Updated the main heading from "Launching July 1st, 2024" to "Supercharge your bookmarks today."
- Revised the supporting text from "Sign up for the waitlist and be the first to try Supermemory" to "Start using Supermemory now and unlock your second brain."
- Changed the button text from "Sign in" to "Get Started."
- None noted in this submission; the focus is on content updates rather than new functionality.
- Simplified the text structure for clarity and engagement, enhancing the overall …

chore: update the cta component after launch

---

apps/web/app/(auth)/onboarding/page.tsx

This pull request aims to improve the onboarding page's styling and accessibility by modifying the background overlay and image properties to prevent pointer events, enhancing user interaction.
- Key Changes: Updated the background overlay to include `pointer-events-none`, preventing user interactions with the background elements.
- New Features: None identified in this submission.
- Refactoring: Adjusted the image class to also include `pointer-events-none`, ensuring that the image does not interfere with user interactions.
<details>
<details>
</details>

Fix: Making links clickable in onboarding section in Step2

---

apps/extension/content/ContentApp.tsx

- Purpose: Adds a draggable UI element to the extension that allows the user to adjust the vertical position of the extension on the page.
- Key Changes:
- Added a new state variable `position` to track the vertical position of the extension.
- Implemented a draggable UI element that can be used to adjust the vertical position of the extension.
- Added event listeners to handle mouse movement and dragging of the UI element.
- Implemented logic to ensure the UI element stays within the viewport.
- Added a dismiss button to the extension UI.
- Impact: This change allows users to customize the position of the extension on the page, improving the user experience and making it easier to access the extension's functionality.
<details> …

feat: Drag and Dismiss extension features

---

apps/extension/content/ContentApp.tsx

- **Purpose:**
Adjust the positioning of the extension popover to improve its appearance and usability.
- Changed the `position` property of the popover from `"absolute"` to `"fixed"` to ensure it stays in the same location on the page.
- Removed the `min-h-screen` class from the main container, allowing the popover to be positioned relative to the content height.
- Adjusted the vertical positioning of the popover to be based on the `position.y` value, ensuring it appears at the correct location.
- **Impact:**
These changes will improve the visual presentation and user experience of the extension popover, making it more intuitive and easier to access.
<details> …

fix: Extension UI fix and Scroll issue with the page scroll

---

apps/extension/content/ContentApp.tsx

- **Purpose:**
Improve the hover behavior and visibility of a UI element in the Content App.
- Modify the CSS class to toggle the visibility of the UI element based on the hover state.
- Adjust the `translate-x` property to smoothly transition the element into view when hovered over or focused.
- Add a custom cursor style using an encoded SVG image.
- **Impact:**
These changes will enhance the user experience by making the UI element more visible and accessible when the user interacts with the Content App.
<details>
</details>

fix: horizontal overflow issue for extension

---

apps/extension/content/ContentApp.tsx

- **Purpose:**
Modify the positioning of the content app elements to improve user experience.
- Changed the `position` property of the main content app element from `absolute` to `fixed`.
- Changed the `position` property of the popover trigger element from `absolute` to `fixed`.
- **Impact:**
These changes will ensure the content app elements remain visible and accessible as the user scrolls the page, enhancing the overall usability of the extension.
<details>
</details>

fix: drag and import icons scrolling over page

---

apps/web/app/api/store/helper.ts

- **Purpose:**
Refactor the logic for saving content to the database to improve performance and error handling.
- Removed the redundant logic for constructing the `saveToDbUrl` and `noteId` values.
- Simplified the database insertion logic to use a single `insert` operation.
- Added better error handling to handle unique constraint violations and other database errors.
- Moved the logic for adding the many-to-many relationship between content and spaces to a separate code block.
- **Impact:**
The changes should improve the reliability and efficiency of the content saving process, reducing the risk of errors and improving the overall user experience.
<details>
</details>

fix: duplicate content saving data in extension

---

apps/web/app/components/memories/AddMemory.tsx

Reverts supermemoryai/supermemory#325

Revert "Updated AddMemory.tsx component to fix overflow memory category/tabs UI  "

---

packages/lib/auth-context.tsx
packages/ui/pages/login.tsx

This PR differs slightly from the one I opened in the monorepo in that this one only stores the last use state when the auth was successful.

feat: add 'last used' badge to login page

---

.github/workflows/publish-ai-sdk.yml
.gitignore
bun.lock
packages/ai-sdk/src/tools.test.ts
packages/ai-sdk/src/tools.ts
packages/openai-sdk-python/README.md
packages/openai-sdk-python/pyproject.toml
packages/openai-sdk-python/src/__init__.py
packages/openai-sdk-python/src/infinite_chat.py
packages/openai-sdk-python/src/tools.py
packages/openai-sdk-python/tests/__init__.py
packages/openai-sdk-python/tests/test_infinite_chat.py
packages/openai-sdk-python/tests/test_tools.py
packages/openai-sdk-python/uv.lock
packages/openai-sdk-ts/.npmignore
packages/openai-sdk-ts/README.md
packages/openai-sdk-ts/package.json
packages/openai-sdk-ts/src/index.ts
packages/openai-sdk-ts/src/infinite-chat.test.ts
packages/openai-sdk-ts/src/infinite-chat.ts
packages/openai-sdk-ts/src/tools.test.ts
packages/openai-sdk-ts/src/tools.ts
packages/openai-sdk-ts/tsconfig.json
packages/openai-sdk-ts/tsdown.config.ts

feat: openai js and python sdk utilities

---

apps/web/components/connect-ai-modal.tsx
apps/web/components/menu.tsx

[Screen Recording 2025-08-31 at 12.03.49 PM.mov <span class="graphite__hidden">(uploaded via Graphite)</span> <img class="graphite__hidden" src="https://app.graphite.dev/user-attachments/thumbnails/f6c88b1f-9f16-47aa-8d5f-6cde61b61e4f.mov" />](https://app.graphite.dev/user-attachments/video/f6c88b1f-9f16-47aa-8d5f-6cde61b61e4f.mov)

feat: redesign MCP connection flow with step-based UI and v1 migration

---

apps/web/app/page.tsx

ux: support integration
